apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mindustry-server
  namespace: argo
spec:
  destination:
    namespace: mindustry
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/Delsynn/NA.git
    targetRevision: HEAD
  info:
    - name: 'mindustry-server'
      value: 'https://mindustry-server.47.cc.ucll.cloud'